[manifest]
version = "1.0.0"
dump_lua = true
priority = 99999999

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''_pool[#_pool + 1] = v.key
                _pool_size = _pool_size + 1
            else
                _pool[#_pool + 1] = 'UNAVAILABLE'
            end'''
position = "before"
payload = '''
if G.GAME.starting_params.showmandeck then
    if G.GAME.used_jokers[v.key] and not G.GAME.banned_keys[v.key] then
        for i = 1, 2 do
            _pool[#_pool + 1] = v.key
            _pool_size = _pool_size + 1
        end
    end
end
'''
match_indent = true
